config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  get "about-us", to: "about#index", as: :about

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  root to: "main#index"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets
  

end
 #don't understand any of this.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
    #what is this??
end

# why do we need a current.rb model? Wouldn't this come under user?
# what is CurrentAttributes??

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets

  validates :username, uniqueness: true
end

app/models/user.rb
# email:string
# password_digest:string
# 
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets

    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
        #need help understanding regex and how it's structured
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    #what is before action?? 

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
            # why do we need a current.rb model? Wouldn't this come under user?
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
  
    
end


# flash[:notice] = "Logged in successfully"
#         flash[:alert] = "Invalid email or password"

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        
        twitter_account.update(
            name: auth.info.name,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret,
        )

        redirect_to root_path, notice: "Successfully connected your account" 

    end

    def auth
        request.env['omniauth.auth'] 
    end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
      
    end

    def create
      @user = User.find_by(email: params[:email])

      if @user.present?

        PasswordMailer.with(user: @user).reset.deliver_now
      end
      redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
      rescure ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your link has expired. Please try again."
    end

    def update
      @user = User.find_signed!(params[:token], purpose: "password_reset")
      if @user.update(password_params)
        redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
      else
        render :edit
      end
    end

    private

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    
    def edit

    end

    def update
       if Current.user.update(password_params)
        redirect_to root_path, notice: "Password updated!"
    else
        render :edit
       end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
      @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new
        end
    end
  
# need to understand params and session - wouldn't have come up with this on my own.
# what is session?
    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    
    end

    def create
      user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

    def destroy
    session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"

  end
end

#where does authenticate method come from?

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in

    def index
        @tweets = Current.user.tweets
    end

    

end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]
    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_account.destroy
        redirect_to twitter_accounts_path, notice: "Successfully removed @#{@twitter_account.username}"
    end 

    private
    def set_twitter_account
        @twitter_account = Current.user.twitter_accounts.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render partial: "shared/navbar" %>

  <div class="container">
  <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Scheduled Tweets</h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>

      <div class="mb-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= f.label :password_confirmation %> 
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
     </div>

     <div class="mb-3">
        <%= f.submit "Reset Password", class: "btn btn-primary" %>
     </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |f| %>

    <div class="mb-3">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", placeholder: "john@gmail.com" %>
    </div>
     <div class="mb-3">
        <%= f.submit "Reset Password", class: "btn btn-primary" %>
     </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to  "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to  "Tweets", tweets_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to  "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to  "About", about_path, class: "nav-link" %>
        </li>
      </ul>


    <ul class="navbar-nav ms-auto mb-2 mg-lg-0">
       <% if Current.user %>
       <li class="nav-item">
       <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
       </li>
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
       <% else %>
       <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
       </li>
       <% end %>
    </ul>

    </div>
  </div>
</nav>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Tweets</h1>

<% if Current.user.twitter_accounts.any? %>
<%= link_to "Schedule   " %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
    <h1>Twitter Accounts</h1>
    <%= link_to "Connect a Twitter Account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
</div>

<% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex algin-items-center mb-4">
        <div class="me-4">
            <%= image_tag twitter_account.image, class: "rounded-circle" %>
            <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
        </div>
        <%= button_to "Disconnect", twitter_account, method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
<% end%>